version: '3'

services:
  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=botwinder
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes # This is a development only Docker
  web:
    build: .
    restart: always
    volumes:
      - .:/var:Z
    ports:
      - "8000:8000"
    dns:
      - 1.1.1.1
      - 1.0.0.1
    depends_on:
      - db
