version: '3'

services:
  db:
    image: mariadb
    restart: always
    environment:
    - MYSQL_DATABASE=botwinder
    - MYSQL_USER=root
    - MYSQL_PASSWORD=
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes # This is a development only Docker
  web:
    image: nginx:latest
    restart: always
    volumes:
    - ./:/app
    - ./vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "8080:80"
    depends_on:
    - app
  app:
    image: php:7.2-fpm
    volumes:
    - ./:/app
    depends_on:
    - db
    - composer
    - node
  node:
    image: node:8
    restart: always
    command: "/bin/bash -c 'cd /app && yarn install && yarn run watch-poll'"
    volumes:
    - ./www:/app
  composer:
    restart: 'no'
    image: composer
    command: install
    volumes:
    - ./www:/app